# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'ko-KR'
early_access: false
reviews:
  profile: 'assertive'
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  auto_review:
    enabled: true
    drafts: false
  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true
chat:
  auto_reply: true
